function canvas() {
	document.write("<!DOCTYPE html>");
	document.write("<html>");
	document.write("	<head>");
	document.write("		<meta charset=\"utf-8\" \/>");
	document.write("		<title><\/title>");
	document.write("		<style type=\"text\/css\">");
	document.write("			html,");
	document.write("			body,");
	document.write("			.tb {");
	document.write("				width: 100%;");
	document.write("				height: 100%;");
	document.write("				padding: 0;");
	document.write("				margin: 0;");
	document.write("			}");
	document.write("");
	document.write("			.tb {");
	document.write("");
	document.write("				display: grid;");
	document.write("				grid-definition-columns: 1fr 1fr 1fr 1fr;");
	document.write("				\/* 			grid-definition-rows: 1fr 1fr; *\/");
	document.write("");
	document.write("			}");
	document.write("");
	document.write("");
	document.write("			canvas {");
	document.write("				background-color: darksalmon;");
	document.write("				border: 1px solid black;");
	document.write("			}");
	document.write("");
	document.write("			.tu {");
	document.write("				width: 100%;");
	document.write("				height: 100%;");
	document.write("				position: absolute;");
	document.write("");
	document.write("				display: flex;");
	document.write("				grid-definition-columns: 1fr 1fr 1fr 1fr;");
	document.write("				text-align: center;");
	document.write("				\/* 水平方向居中 *\/");
	document.write("				justify-content: center;");
	document.write("				\/* 弹性盒子当中横轴方向居中 *\/");
	document.write("			}");
	document.write("");
	document.write("			a {");
	document.write("				width: 0px;");
	document.write("				height: 0px;");
	document.write("");
	document.write("			}");
	document.write("		<\/style>");
	document.write("	<\/head>");
	document.write("	<body>");
	document.write("");
	document.write("		<div class=\"tu\">");
	document.write("");
	document.write("			<div style=\"margin-right:2px;\">");
	document.write("				<div>");
	document.write("					<canvas id=\"sx\"><\/canvas>");
	document.write("				<\/div>");
	document.write("				<div>");
	document.write("");
	document.write("					<canvas id=\"zh\"><\/canvas>");
	document.write("				<\/div>");
	document.write("			<\/div>");
	document.write("			<div>");
	document.write("				<div>");
	document.write("");
	document.write("					<canvas id=\"sd\"><\/canvas>");
	document.write("				<\/div>");
	document.write("				<div>");
	document.write("					<canvas id=\"zx\"><\/canvas>");
	document.write("				<\/div>");
	document.write("			<\/div>");
	document.write("			<a href='index.html' style=\"background-color: aqua;align-items: center;text-align: center;\">");
	document.write("				<button>点击返回<\/button>");
	document.write("			<\/a>");
	document.write("		<\/div>");
	document.write("");
	document.write("");
	document.write("		<script type=\"text\/javascript\">");
	document.write("			var sdxy = [{");
	document.write("				x: 10,");
	document.write("				y: 20");
	document.write("			}, {");
	document.write("				x: 40,");
	document.write("				y: 40");
	document.write("			}, {");
	document.write("				x: 280,");
	document.write("				y: 140");
	document.write("			}, {");
	document.write("				x: 280,");
	document.write("				y: 10");
	document.write("			}, {");
	document.write("				x: 0,");
	document.write("				y: 0");
	document.write("			}]");
	document.write("");
	document.write("");
	document.write("			var sd = document.getElementById(\"sd\").getContext(\"2d\");");
	document.write("");
	document.write("");
	document.write("");
	document.write("			for (let i = 0; i < sdxy.length - 1; i++) {");
	document.write("				sd.beginPath();");
	document.write("");
	document.write("				sd.fillStyle = `rgb(${Math.random()*255},${Math.random()*255},${Math.random()*255})`;");
	document.write("");
	document.write("");
	document.write("");
	document.write("				sd.arc(sdxy[i].x, sdxy[i].y, 10, 0, Math.PI * 2, true);");
	document.write("				let x = sdxy[i + 1].x;");
	document.write("				let y = sdxy[i + 1].y;");
	document.write("				sd.moveTo(x, y);");
	document.write("				sd.fill();");
	document.write("");
	document.write("			}");
	document.write("");
	document.write("");
	document.write("");
	document.write("			var zht = [100, 200, 50, 70]");
	document.write("			var zh = document.getElementById(\"zh\").getContext(\"2d\");");
	document.write("");
	document.write("			for (let i = 0; i < zht.length; i++) {");
	document.write("				zh.fillStyle = `rgb(${Math.random()*255},${Math.random()*255},${Math.random()*255})`;");
	document.write("");
	document.write("				zh.fillRect(i * 10, 150 - zht[i], 10, zht[i]); \/\/左上角x坐标，左上角y坐标，宽度，长度");
	document.write("");
	document.write("			}");
	document.write("");
	document.write("");
	document.write("");
	document.write("			var sxs = [100, 200, 50, 50]; \/\/");
	document.write("			var colors = [\"red\", \"orange\", \"yellow\", \"blue\"];");
	document.write("			var fm = 0;");
	document.write("			for (let i = 0; i < sxs.length; i++) {");
	document.write("				fm = fm + sxs[i];");
	document.write("			}");
	document.write("");
	document.write("			var sx = document.getElementById(\"sx\").getContext(\"2d\");");
	document.write("");
	document.write("			\/\/ sx.beginPath();");
	document.write("			\/\/ sx.moveTo(150,75);");
	document.write("			\/\/ sx.arc(150,75,75,0,Math.PI*0.25,false);");
	document.write("			\/\/ sx.fill();");
	document.write("			var beginange = 0");
	document.write("			var endange = 0;");
	document.write("			for (let i = 0; i < sxs.length; i++) {");
	document.write("");
	document.write("");
	document.write("				endange = endange + sxs[i] \/ fm;");
	document.write("");
	document.write("");
	document.write("				sx.beginPath();");
	document.write("");
	document.write("				sx.fillStyle = colors[i];");
	document.write("");
	document.write("");
	document.write("");
	document.write("");
	document.write("				if (i == 2) {");
	document.write("					sx.moveTo(152, 70); \/\/移动到152，70");
	document.write("					sx.arc(152, 70, 65, 2 * Math.PI * beginange, 2 * Math.PI * endange, false);");
	document.write("					sx.lineTo(152, 70)");
	document.write("				} else {");
	document.write("");
	document.write("					sx.moveTo(150, 75);");
	document.write("					console.log(beginange)");
	document.write("					console.log(endange)");
	document.write("");
	document.write("					sx.arc(150, 75, 65, 2 * Math.PI * beginange, 2 * Math.PI * endange, false);");
	document.write("");
	document.write("					sx.fill();");
	document.write("");
	document.write("					sx.lineTo(150, 75)");
	document.write("");
	document.write("				}");
	document.write("");
	document.write("");
	document.write("");
	document.write("");
	document.write("");
	document.write("");
	document.write("				sx.strokeStyle = \"black\";");
	document.write("				sx.stroke();");
	document.write("");
	document.write("");
	document.write("");
	document.write("				beginange = endange;");
	document.write("");
	document.write("");
	document.write("				\/\/	 endange = endange+beginange;");
	document.write("");
	document.write("");
	document.write("				console.log(\"--------------------\")");
	document.write("");
	document.write("			}");
	document.write("");
	document.write("");
	document.write("");
	document.write("			var zxxy = [{");
	document.write("				x: 30,");
	document.write("				y: 20");
	document.write("			}, {");
	document.write("				x: 60,");
	document.write("				y: 40");
	document.write("			}, {");
	document.write("				x: 90,");
	document.write("				y: 40");
	document.write("			}, {");
	document.write("				x: 120,");
	document.write("				y: 90");
	document.write("			}, {");
	document.write("				x: 150,");
	document.write("				y: 120");
	document.write("			}, {");
	document.write("				x: 180,");
	document.write("				y: 90");
	document.write("			}, {");
	document.write("				x: 210,");
	document.write("				y: 50");
	document.write("			}, {");
	document.write("				x: 240,");
	document.write("				y: 30");
	document.write("			}, {");
	document.write("				x: 270,");
	document.write("				y: 10");
	document.write("			}]");
	document.write("			var zx = document.getElementById(\"zx\").getContext(\"2d\");");
	document.write("");
	document.write("			for (let i = 0; i < zxxy.length - 1; i++) {");
	document.write("				zx.beginPath();");
	document.write("				zx.arc(zxxy[i].x, zxxy[i].y, 2, 0, Math.PI * 2, true);");
	document.write("				let x = zxxy[i + 1].x;");
	document.write("				let y = zxxy[i + 1].y;");
	document.write("				zx.moveTo(x, y);");
	document.write("				zx.fill();");
	document.write("				console.log(i)");
	document.write("				if (i == 0) {");
	document.write("					zx.beginPath();");
	document.write("					zx.moveTo(0, 0);");
	document.write("					zx.lineTo(zxxy[i].x, zxxy[i].y);");
	document.write("					zx.stroke();");
	document.write("				} else {");
	document.write("					\/*上一个点*\/");
	document.write("					zx.beginPath();");
	document.write("					zx.moveTo(zxxy[i - 1].x, zxxy[i - 1].y);");
	document.write("					zx.lineTo(zxxy[i].x, zxxy[i].y);");
	document.write("					zx.stroke();");
	document.write("				}");
	document.write("			}");
	document.write("		<\/script>");
	document.write("");
	document.write("	<\/body>");
	document.write("<\/html>");
	document.write("");
}
